project_name: tjlike_agenda

builds:
  - binary: tjlike_agenda
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64

archives:
  - id: default
    files:
      - sources.yaml
  - id: windows
    format_overrides:
      - goos: windows
        format: zip
