project_name: tjlike_agenda

builds:
  - binary: tjlike_agenda
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64

archives:
    - files:
      - config.yaml
      - api.yml
      - README.md
      - LICENSE
      - CHANGELOG.md
      format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch