name: CICD

on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'

      - name: Install dependencies
        run: |
          go version
          go get .

      - name: Run build
        run: go build .

      - name: Run vet & lint
        run: |
          go vet .

      - name: Run tests
        run: make test
